# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keyboard_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16keyboard_message.proto\x12\x04main\"|\n\x08Keyboard\x12%\n\x06layout\x18\x01 \x01(\x0e\x32\x15.main.Keyboard.Layout\x12\x0f\n\x07\x62\x61\x63klit\x18\x02 \x01(\x08\"8\n\x06Layout\x12\n\n\x06UNKOWN\x10\x00\x12\n\n\x06QWERTY\x10\x01\x12\n\n\x06QWERTZ\x10\x02\x12\n\n\x06\x44VORAK\x10\x03\x42\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'keyboard_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _KEYBOARD._serialized_start=32
  _KEYBOARD._serialized_end=156
  _KEYBOARD_LAYOUT._serialized_start=100
  _KEYBOARD_LAYOUT._serialized_end=156
# @@protoc_insertion_point(module_scope)
