# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: memory_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14memory_message.proto\x12\x04main\"\x98\x01\n\x06Memory\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x1f\n\x04unit\x18\x02 \x01(\x0e\x32\x11.main.Memory.Unit\"^\n\x04Unit\x12\n\n\x06UNKOWN\x10\x00\x12\x07\n\x03\x42IT\x10\x01\x12\x08\n\x04\x42YTE\x10\x02\x12\x0c\n\x08KILOBYTE\x10\x03\x12\x0c\n\x08MEGABYTE\x10\x04\x12\x0c\n\x08GIGABYTE\x10\x05\x12\r\n\tTERRABYTE\x10\x06\x42\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'memory_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _MEMORY._serialized_start=31
  _MEMORY._serialized_end=183
  _MEMORY_UNIT._serialized_start=89
  _MEMORY_UNIT._serialized_end=183
# @@protoc_insertion_point(module_scope)
