# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processor_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import memory_message_pb2 as memory__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17processor_message.proto\x12\x04main\x1a\x14memory_message.proto\"k\n\x03\x43PU\x12\r\n\x05\x62rand\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x63ores\x18\x03 \x01(\r\x12\x16\n\x0enumber_threads\x18\x04 \x01(\r\x12\x0f\n\x07min_ghz\x18\x05 \x01(\x01\x12\x0f\n\x07max_ghz\x18\x06 \x01(\x01\"b\n\x03GPU\x12\r\n\x05\x62rand\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07min_ghz\x18\x03 \x01(\x01\x12\x0f\n\x07max_ghz\x18\x04 \x01(\x01\x12\x1c\n\x06memory\x18\x05 \x01(\x0b\x32\x0c.main.MemoryB\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'processor_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _CPU._serialized_start=55
  _CPU._serialized_end=162
  _GPU._serialized_start=164
  _GPU._serialized_end=262
# @@protoc_insertion_point(module_scope)
