# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: screen_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14screen_message.proto\x12\x04main\"\xcd\x01\n\x06Screen\x12\x11\n\tsize_inch\x18\x01 \x01(\x02\x12+\n\nresolution\x18\x02 \x01(\x0b\x32\x17.main.Screen.Resolution\x12!\n\x05panel\x18\x03 \x01(\x0e\x32\x12.main.Screen.Panel\x12\r\n\x05touch\x18\x04 \x01(\x08\x1a+\n\nResolution\x12\r\n\x05width\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\r\"$\n\x05Panel\x12\n\n\x06UNKOWN\x10\x00\x12\x07\n\x03IPS\x10\x01\x12\x06\n\x02VA\x10\x02\x42\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'screen_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _SCREEN._serialized_start=31
  _SCREEN._serialized_end=236
  _SCREEN_RESOLUTION._serialized_start=155
  _SCREEN_RESOLUTION._serialized_end=198
  _SCREEN_PANEL._serialized_start=200
  _SCREEN_PANEL._serialized_end=236
# @@protoc_insertion_point(module_scope)
