# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage_message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import memory_message_pb2 as memory__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15storage_message.proto\x12\x04main\x1a\x14memory_message.proto\"v\n\x07Storage\x12$\n\x06\x64river\x18\x01 \x01(\x0e\x32\x14.main.Storage.Driver\x12\x1c\n\x06memory\x18\x02 \x01(\x0b\x32\x0c.main.Memory\"\'\n\x06\x44river\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x07\n\x03HDD\x10\x01\x12\x07\n\x03SSD\x10\x02\x42\x06Z\x04./pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'storage_message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\004./pb'
  _STORAGE._serialized_start=53
  _STORAGE._serialized_end=171
  _STORAGE_DRIVER._serialized_start=132
  _STORAGE_DRIVER._serialized_end=171
# @@protoc_insertion_point(module_scope)
